version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./..:/app
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
    dns: 8.8.8.8
    restart: always
    volumes:
      - ./..:/app
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_secret
      MYSQL_ROOT_PASSWORD: db_secret
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
